### ISSUE TITLE
encode all -0 values as floats

### ISSUE THREAD

**Issue by emattson** [shapesecurity/superpack-js#8]

**Comment by michaelficarra** [comment]
To clarify, @emattson is pointing out that `-0` is encoded as a negative integer value with magnitude `0` instead of the float or double `-0` value. I can make arguments for either encoding, but I'd like to hear what others think. Should `-0` be encoded to an integer, float, double, or something else?

**Comment by LewisJEllis** [comment]
I think a reasonable resolution to both this and shapesecurity/superpack-spec#1 would be to require (in the spec) that any -0 value be encoded as a float. Maybe there's one out there, but I can't think of any languages with a type that represents -0 values aside from float/double. Five bytes isn't the most size-optimal, but how often is anyone trying to encode -0?

**Comment by michaelficarra** [comment]
I like it.
